import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import WidgetAppBar from "@/components/appBar/widget";
import WidgetCardInfo from "@/components/CardInfo/widget";
import WidgetTopics from "@/components/Topics/widget";
import WidgetProjects from "@/components/Projects/widget";
import WidgetBottomBar from "@/components/Bottombar/widget";
import WidgetPost from "@/components/post/widget";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import WidgetNotFound from "@/components/notFound/widget";

export default function Home() {
  const [data, setdata] = useState();
  const [load, setload] = useState(false);
  const [erro, seterro] = useState(false);
  const r = useRouter();
  const { v } = r.query;
  useEffect(() => {
    if (!load && v) {
      fetch(`http://localhost:3000/api/getonedata?titulo=${v}`)
        .then((e) => e.json())
        .then((e) => {
          setload(true);
          console.log(e);
          if (e.data.length == 0) {
            seterro(true);
          }
          setdata(e.data[0]);
          setload(true);
        })
        .catch((e) => {
          console.log(e);
          seterro(true);
        });
    }
  }, [v]);
  return (
    <>
      <Head>
        <title>Projet </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="colunm">
        <div className="colunm1">
          <WidgetAppBar />
          {erro ? <WidgetNotFound e={v} /> : <WidgetPost data={data} />}
          <WidgetTopics />
          <WidgetBottomBar />
        </div>
      </div>
    </>
  );
}
