import Head from "next/head";
import WidgetAppBar from "./../components/appBar/widget";
import WidgetCardInfo from "./../components/CardInfo/widget";
import WidgetTopics from "./../components/Topics/widget";
import WidgetProjects from "./../components/Projects/widget";
import WidgetBottomBar from "./../components/Bottombar/widget";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="colunm">
        <div className="colunm1">
          <WidgetAppBar />
          <WidgetProjects />
          <WidgetBottomBar />
        </div>
      </div>
    </>
  );
}
